# Generated by Django 3.1 on 2021-05-18 12:51

import app.models
import ckeditor.fields
import ckeditor_uploader.fields
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Ushlab qolish yoki qo'shimcha to'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Kompaniya telefon raqami')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya manzili')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya asoschisi')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Kompaniya haqida qisqacha ma'lumot")),
                ('video', models.FileField(blank=True, null=True, upload_to='company/video/', verbose_name='Kompaniya haqida qisqacha video')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Bot uchun qisqacha ma'lumot")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/image/', verbose_name='Kompaniya logotipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Kompaniya ma'lumotini qo'shish",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lavozim nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name_plural': 'Lavozim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Jinsi')),
                ('tabel_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tabel raqami')),
                ('start_work_at', models.DateField(blank=True, null=True, verbose_name='Ish boshlagan sana')),
                ('account_number', models.BigIntegerField(blank=True, null=True, verbose_name='Xisob raqami')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Elektron manzil')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobil telefon')),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Uy telefoni')),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Ish telefoni')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uy manzili')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/staff/image/', verbose_name='Xodimning rasmi')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department', verbose_name="Bo'lim")),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Lavozim')),
            ],
            options={
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya turini nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Xodimlaring qo'shimcha dam olish turi",
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_hour', models.BooleanField(default=False, verbose_name='Soatbay')),
                ('per_day', models.BooleanField(default=False, verbose_name='Kunbay')),
                ('start_at', models.DateField(verbose_name='Boshlash vaqti')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Izoh')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim')),
                ('vacation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacationtype', verbose_name="Qo'shimcha dam olish turi")),
            ],
            options={
                'verbose_name_plural': "Xodimlaring qo'shimcha dam olish bo'limi",
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Lavozimga qo'yiladigan talablar haqida ma'lumot")),
                ('is_active', models.BooleanField(default=False, verbose_name='Vakansiya aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Lavozimga vakansiya')),
            ],
            options={
                'verbose_name_plural': 'Vakansiya',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ishlash turi(soatbay, kunbay, ishbay ...)')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Miqdori')),
                ('attached_date', models.DateField(blank=True, null=True, verbose_name='Biriktirilgan sana')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name_plural': 'Ish haqqi',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True, verbose_name='Savol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
            options={
                'verbose_name_plural': "Bo'lim savoli",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge', models.BooleanField(default=False, verbose_name='Jarima')),
                ('reward', models.BooleanField(default=False, verbose_name='Mukofot')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name_plural': "Xodimlarga jarima mukofot e'lon qilish",
            },
        ),
        migrations.CreateModel(
            name='NewStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Xodimning to'liq ism sharifi")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Xodimning tug'ilgan sanasi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/staff/image/', verbose_name='Xodimning rasmi')),
                ('period_time', models.DateField(blank=True, null=True, verbose_name='Stajirovka mudati')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tg_user_id', models.IntegerField(blank=True, null=True)),
                ('question_step', models.IntegerField(blank=True, null=True)),
                ('tg_answer_id', models.IntegerField(blank=True, null=True)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department', verbose_name="Xodim ishlaydigan bo'lim")),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Xodimning lavozimi')),
            ],
            options={
                'verbose_name_plural': 'Yangi xodimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came', models.DateTimeField(verbose_name='Kelishi')),
                ('went', models.DateTimeField(verbose_name='Ketishi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name_plural': 'Hodimlarning kelib ketishi',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('date_of_issue', models.DateField(verbose_name='Berilgan sana')),
                ('validity_period', models.DateField(verbose_name='Amal qilish mudati')),
                ('document', models.FileField(upload_to=app.models.get_directory, verbose_name='Hujjat(file)')),
                ('note', models.CharField(max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.typecompany', verbose_name='Kompaniya turi'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Filial')),
            ],
            options={
                'verbose_name_plural': 'Filial',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=512, verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.newstaff', verbose_name='Yangi Xodim')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name="Bo'lim savoli")),
            ],
            options={
                'verbose_name_plural': 'Javoblar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_date', models.DateField(blank=True, null=True, verbose_name='Biriktirilgan sana')),
                ('find', models.BooleanField(default=False, verbose_name='Ushlab qolish')),
                ('additional_payment', models.BooleanField(default=False, verbose_name="Qo'shimcha to'lov")),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.additionalpaymenttype', verbose_name='Turi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name_plural': "Ushlab qolish yoki to'lov qo'shish",
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_director', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'HR',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
