# Generated by Django 3.1 on 2021-05-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='amount_of_staff',
            field=models.IntegerField(default=1, verbose_name='Hodimlar soni'),
        ),
    ]
