# Generated by Django 3.1 on 2021-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superstaffs',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
