# Generated by Django 3.1 on 2021-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalpayments',
            name='additional_payment',
        ),
        migrations.RemoveField(
            model_name='additionalpayments',
            name='find',
        ),
        migrations.AddField(
            model_name='additionalpayments',
            name='type_of_additional_payment',
            field=models.CharField(choices=[('find', 'Ushlab qolish'), ('additional_payment', "Qo'shimcha to'lov")], default=0, max_length=225),
            preserve_default=False,
        ),
    ]
