# Generated by Django 3.1 on 2021-06-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210615_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininganswer',
            name='answer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainingquestion', verbose_name='Savol'),
        ),
    ]
