# Generated by Django 3.1 on 2021-05-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_amount_of_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorlPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ish Rejasi',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='work_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.worlplan', verbose_name='Ish rejasi'),
        ),
    ]
