# Generated by Django 3.1 on 2021-05-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210523_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalpaymenttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
    ]
