# Generated by Django 3.1 on 2021-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210615_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininganswer',
            name='answer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Javob'),
        ),
    ]
