# Generated by Django 3.1 on 2022-05-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220528_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='staff_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
