# Generated by Django 3.1 on 2021-06-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210615_2155'),
        ('app', '0003_auto_20210615_2202'),
    ]

    operations = [
    ]
