# Generated by Django 3.1 on 2022-05-31 21:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_position_staff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.position'),
        ),
    ]
