# Generated by Django 3.1 on 2021-05-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210520_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='work_plan',
        ),
        migrations.AddField(
            model_name='worlplan',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
            preserve_default=False,
        ),
    ]
