# Generated by Django 3.1 on 2021-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_additionalpaymenttype_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='per_day',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='per_hour',
        ),
        migrations.AddField(
            model_name='vacation',
            name='vocation_period_types',
            field=models.CharField(blank=True, choices=[('per_hour', 'Soatbay'), ('per_day', 'Kunbay')], max_length=255, null=True, verbose_name='Turi'),
        ),
    ]
