# Generated by Django 3.1 on 2021-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210521_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecompany',
            options={'verbose_name_plural': 'Kompaniya turi'},
        ),
        migrations.AddField(
            model_name='salary',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yankunlangan sana'),
        ),
    ]
