# Generated by Django 3.1 on 2021-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210521_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorlPlan',
            new_name='WorkPlan',
        ),
    ]
