# Generated by Django 3.1 on 2021-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staff_training_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='training_url',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
