# Generated by Django 3.1 on 2022-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220531_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', 'Mужчина'), ('female', 'Женщина')], max_length=10, verbose_name='Jinsi'),
        ),
    ]
