# Generated by Django 3.1 on 2021-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210521_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='company/staff/qr_code/', verbose_name='Xodimning qr code'),
        ),
    ]
