# Generated by Django 3.1 on 2021-06-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_admin_bot_entrytext_finishtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='bot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='entrytext',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='finishtext',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
    ]
