# Generated by Django 3.1 on 2021-06-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210616_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingquestion',
            name='training_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.traininginfo'),
        ),
    ]
