# Generated by Django 3.1 on 2021-06-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210608_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Kompaniya'),
        ),
    ]
