# Generated by Django 3.1 on 2021-06-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_trainingquestion_training_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingquestion',
            name='training_info',
        ),
    ]
