# Generated by Django 3.1 on 2022-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220531_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспортные данныеi'),
        ),
    ]
