# Generated by Django 3.1 on 2021-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_admin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bo'lim haqida"),
        ),
        migrations.AddField(
            model_name='position',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim haqida'),
        ),
    ]
