# Generated by Django 3.1 on 2021-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_trainingquestion_training_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='came',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kelishi'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='went',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ketishi'),
        ),
    ]
