# Generated by Django 3.1 on 2021-06-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_companyculture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('start_work', models.TimeField(verbose_name='Ish boshlanishi')),
                ('lunch_start', models.TimeField(verbose_name='Tushlik vaqti')),
                ('lunch_end', models.TimeField(verbose_name='Tushlik tugash vaqti')),
                ('end_work', models.TimeField(verbose_name='Ish Tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
