# Generated by Django 3.1 on 2021-06-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_traininginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininginfo',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
