# Generated by Django 3.1 on 2021-06-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_traininginfo_departament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininginfo',
            name='departament',
        ),
        migrations.AddField(
            model_name='traininginfo',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.position', verbose_name='Xodimning lavozimi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
