# Generated by Django 3.1 on 2021-06-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_traininganswer_trainingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininganswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='Xodim'),
        ),
    ]
